### ISSUE TITLE
chrony SHM permission setting

### ISSUE THREAD

**Issue by seiga-k** [vooon/ntpd_driver#3]
When I run ntpd_driver with chrony, I got a permission error on shmget().
So, I add a permission setting for chrony.conf file and error was gone.

```
refclock SHM 0:perm=0666 delay 0.5 refid ROS
```

Is this coping correct?
Or, do I need another method?
 
My environment is as bellow.
OS : Ubuntu 16.04
ROS : Kinetic
chrony : 2.1.1 (installed by apt)

**Comment by vooon** [comment]
As i remember, default 0660, so you could add your ros user (typically your user) to chrony group.
But that approach also is good.

**Comment by seiga-k** [comment]
> so you could add your ros user (typically your user) to chrony group.

Okay, I don't know that method. Thanks!
