### ISSUE TITLE
Needs Melodic Release

### ISSUE THREAD

**Issue by JWhitleyWork** [vooon/ntpd_driver#4]
This package is released for up to Lunar but does not have a Melodic release. The package is very useful and would be nice to have in Melodic. Thanks!

**Comment by vooon** [comment]
@JWhitleyAStuff oh, i forgot about it. That you to letting me know. Will be released at this weekend.

**Comment by JWhitleyWork** [comment]
Excellent! Thank you.

**Comment by vooon** [comment]
I'll keep it open as a reminder.

**Comment by vooon** [comment]
Done: https://github.com/ros/rosdistro/pull/21710
