### ISSUE TITLE
SHM permission error

### ISSUE THREAD

**Issue by joshferns** [vooon/ntpd_driver#5]
Hi @vooon  I'm attempting to set up ntpd_driver 
OS : ubuntu 20.04 LTS 
H/W : Raspberry Pi 4
ROS Version : Noetic 
I've built the package from source(unable to locate it on apt)

Using Chrony and configured it as 
`### SHM driver
refclock SHM 0 delay 0.5 refid ROS`

I've configured /etc/sudoers with 
`%sudo	ALL=NOPASSWD: /bin/date`

On trying to run the example 
`rosrun ntpd_driver shm_driver _shm_unit:=0 _time_ref_topic:=/mavros/time_reference`
 
I get the following error 
`[ INFO] [1618212098.567542010]: NTP time source: /mavros/time_reference
[ INFO] [1618212098.569852429]: NTP date fixup: disabled
[FATAL] [1618212098.569990891]: SHM shmget(0x4e545030, 96, 666) fail: Permission denied`

Thanks.

**Comment by vooon** [comment]
Something prevents you from opening shm. For ntpd as i remember need to use shm unit >= 2, but don't remember what needs for chrony.

Problem is similar to gpsd, so that could help: https://gpsd.gitlab.io/gpsd/gpsd-time-service-howto.html
