### ISSUE TITLE
Can't get system to sync with the topic 

### ISSUE THREAD

**Issue by Ahnassef** [vooon/ntpd_driver#6]
Hello

I set up the package and and I'm publishing the sensor_msgs/timereference topic 10 Hz. Also started the node and it says:

SHM(0) key 0x....,successfully opened.

bt when I check chronyc sources, it gives all zeros. 

Any help would be appreciated.

**Comment by vooon** [comment]
What version do you use?

**Comment by Ahnassef** [comment]
@vooon 

I'm using ROS noetic.

**Comment by Ahnassef** [comment]
Hello @vooon, Happy holidays. 

I tried to create a test package with simple timer of 10 Hz and run the ntpd_driver and it works without problem and chrony is tracking flawlessly.

The problem occurs with the ros velodyne driver that publishes pointcloud & GPS time stamp but chrony doesn't track in this case.

Any help would be appreciated.

**Comment by vooon** [comment]
Maybe time jumps too far from system clock? Try to use `~fixup_date: true` (needs `sudo date` rights).

**Comment by its-pru** [comment]
Hey, I'm running into a similar issue and I think it's because of the time jump from the system time to reference time being too large for chrony. I'm getting the error, "ERR: sudo: a password is required". How do I give it sudo permissions? Thanks!

**Comment by vooon** [comment]
@its-pru are you sure that you're followed https://github.com/vooon/ntpd_driver#date-fixup-configuration-sudo ?
Try to execute `sudo /bin/date` from the user running the node.

**Comment by its-pru** [comment]
@vooon I got it working, Thanks!

**Comment by vooon** [comment]
I think i'll close that ticket as stale. Reopen if needed.
