### ISSUE TITLE
ROS Noetic chrony no time sync

### ISSUE THREAD

**Issue by nomah98** [vooon/ntpd_driver#7]
Hello,

I am running ROS Noetic and chrony.

I am running the ntpd_driver with `rosrun _shm_driver:=0 _time_ref_topic:=/mini_2/mavros/time_reference _fixup_enabled:=true __ns:=mini2`. I do not seem to have any permissions issue.

![Screenshot from 2022-07-22 11-48-37](https://user-images.githubusercontent.com/28277346/180476562-a8e956d3-a5ce-4af7-867b-200ab53a2d6f.png)

My /etc/chrony/chrony.conf file includes `refclock SHM 0 delay 0.5 refid ROS`

Running sudo chronyc sources shows the ROS source as unreachable.

![Screenshot from 2022-07-22 11-51-57](https://user-images.githubusercontent.com/28277346/180478166-e2b9cb10-ca60-4178-96d1-4e99e9822649.png)

`rosnode info /mini_2/ntpd_shm` shows the node is subscribed to my /mini_2/mavros/time_reference topic, which is being published on via a recorded bag as a TimeReference message.
![Screenshot from 2022-07-22 11-54-17](https://user-images.githubusercontent.com/28277346/180478265-06a55265-cc18-43b6-b0b9-be1ba93630b4.png)

![Screenshot from 2022-07-22 11-57-26](https://user-images.githubusercontent.com/28277346/180478302-aa96a04b-14c9-4162-ad49-470f1a9593d2.png)

I am unsure why the source is still shown as unreachable. I installed via apt. I have used the repo previously and installed with catkin in ROS Melodic and have had success with the same setup. Any help would be appreciated

**Comment by vooon** [comment]
Do you have `Setting system date to: <some-date>` message? It looks like topic never got the message.

**Comment by nomah98** [comment]
I do not ever get that message. I can confirm messages are being published to that topic as a sensor_msgs/TimeReference

**Comment by nomah98** [comment]
Is there any other information via ROS or Chrony I can provide to help investigate this?

**Comment by vooon** [comment]
Can you try to send some TimeReference manually via rostopic?
Also could you please enable debug log for the node (use rqt)?
We are looking that message:
https://github.com/vooon/ntpd_driver/blob/b8b9e1d4cc6473a353e469859bf0477c6a8d108e/src/shm_driver.cpp#L155

**Comment by matthewryanburgin191** [comment]
Any update on this issue?

**Comment by vooon** [comment]
Seems no. But note that time ref topic parameter was dropped. Please use remap.
