### ISSUE TITLE
the ntpd_driver needs to other config，like install ntpd or gpsd?

### ISSUE THREAD

**Issue by hunter55555** [vooon/ntpd_driver#8]
hello,thanks for your work, if i want to use this will i need to install some package before?
and can i change the server ip "127.127.28.2" ? 
i want to know details

**Comment by vooon** [comment]
Hi,

Since that node just feeds time sync daemon with time ref topic, you need to have the daemon, either `ntpd` or `chrony`.
For ntpd that one of special addresses which corresponds to shared memory interface, please check ntpd docs.
